apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-collector-config
  labels:
    sampling.policy: baseline_head
    sampling.budget: high
data:
  config.yaml: |
    receivers:
      otlp:
        protocols:
          grpc:
          http:
    processors:
      probabilistic_sampler:
        sampling_percentage: 30
      batch:
        timeout: 1s
        send_batch_size: 1024
    exporters:
      otlp/jaeger:
        endpoint: jaeger-collector.observability.svc.cluster.local:4317
        tls:
          insecure: true
      prometheus:
        endpoint: 0.0.0.0:8889
    service:
      telemetry:
        metrics:
          address: 0.0.0.0:8888
      pipelines:
        traces:
          receivers: [otlp]
          processors: [probabilistic_sampler, batch]
          exporters: [otlp/jaeger]
