apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-collector-config
  labels:
    sampling.policy: ours
    sampling.budget: high
data:
  config.yaml: |
    receivers:
      otlp:
        protocols:
          grpc:
          http:
    processors:
      tail_sampling:
        decision_wait: 10s
        num_traces: 90000
        expected_new_traces_per_sec: 350
        policies:
          - name: svc-productpage-high
            type: and
            and:
              and_sub_policy:
                - name: productpage-attr
                  type: string_attribute
                  string_attribute:
                    key: service.name
                    values: [productpage]
                - name: productpage-sample
                  type: probabilistic
                  probabilistic:
                    sampling_percentage: 25
          - name: svc-reviews-high
            type: and
            and:
              and_sub_policy:
                - name: reviews-attr
                  type: string_attribute
                  string_attribute:
                    key: service.name
                    values: [reviews]
                - name: reviews-sample
                  type: probabilistic
                  probabilistic:
                    sampling_percentage: 35
          - name: svc-ratings-high
            type: and
            and:
              and_sub_policy:
                - name: ratings-attr
                  type: string_attribute
                  string_attribute:
                    key: service.name
                    values: [ratings]
                - name: ratings-sample
                  type: probabilistic
                  probabilistic:
                    sampling_percentage: 20
          - name: error-traces
            type: status_code
            status_code:
              status_codes: [ERROR]
      batch:
        timeout: 1s
    exporters:
      otlp/jaeger:
        endpoint: jaeger-collector.observability.svc.cluster.local:4317
        tls:
          insecure: true
      prometheus:
        endpoint: 0.0.0.0:8889
    service:
      telemetry:
        metrics:
          address: 0.0.0.0:8888
      pipelines:
        traces:
          receivers: [otlp]
          processors: [tail_sampling, batch]
          exporters: [otlp/jaeger]
